// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnebqeghwepwfvxyaozn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZWJxZWdod2Vwd2Z2eHlhb3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODY5ODQsImV4cCI6MjA1NDI2Mjk4NH0.c8ThsehvZh3JwQJKMqU942JaD6ze2BhEfBquuh2ENoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);